// <auto-generated />
namespace Capa.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class relaciones : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(relaciones));
        
        string IMigrationMetadata.Id
        {
            get { return "202008120027415_relaciones"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
